### ISSUE TITLE
启动崩溃

### ISSUE THREAD

**Issue by DLumina** [TowardtheStars/Simple-Automation---MCmod#1]
[crash-2019-01-08_18.40.07-client.txt](https://github.com/TowardtheStars/Simple-Automation---MCmod/files/2736351/crash-2019-01-08_18.40.07-client.txt)
以上是错误报告。

**Comment by DLumina** [comment]
更新之后再次崩溃。
[crash-2019-01-09_00.42.06-client.txt](https://github.com/TowardtheStars/Simple-Automation---MCmod/files/2737648/crash-2019-01-09_00.42.06-client.txt)

**Comment by DLumina** [comment]
你把编译好的jar文件直接提交到github的release吧...这样有更新的话看起来也方便
另外，现在很多模组已经不再提供对forge2768的支持了...例如cuisine

**Comment by DLumina** [comment]
emmmmmmmmm............
[crash-2019-01-10_00.48.54-client.txt](https://github.com/TowardtheStars/Simple-Automation---MCmod/files/2741773/crash-2019-01-10_00.48.54-client.txt)
单mod, forge2768启动崩溃

**Comment by TowardtheStars** [comment]
编译问题，已修复
